#if GGAMETYPE2  == GGAME_MVM
    #define VERSION_NUM "3.0_MVM"
#elseif GGAMETYPE_JAILBREAK == JAILBREAK_ON
    #define VERSION_NUM "3.0_TF2Jail"
#elseif GGAMETYPE == GGAME_CSGO
    #define VERSION_NUM "3.0_CSGO"
#else
    #define VERSION_NUM "3.0_TF2"
#endif

#define eVERSION_NUM "1.2.4.1"

#define REVISION_NUM 12450 //increment every release

#define AUTHORS "Ownz (DarkEnergy), El Diablo and DAGOTHUR"
#define eAUTHORS "PimpinJuice and Ownz (DarkEnergy)"
