name: War3Evo War3Source SourceMod Plugin Workflow

on:
  push:
    branches: master    

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: [ "1.9" ]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Download & Extract SourceMod 1.9
      run: |
        cd ${{ github.workspace }}
        wget "http://www.sourcemod.net/latest.php?version=1.9&os=linux" -O sourcemod.tar.gz
        tar -xzf sourcemod.tar.gz -keep-old-files
         
    - name: Give spcomp the required permissions
      run: chmod +x addons/sourcemod/scripting/spcomp_1.9.0.6261
      
    - name: Clean compiled directory
      run: |
          rm addons/sourcemod/scripting/compiled/*
          
    - name: Switch Game Mode to TF2
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to TF2";
          ./game_switcher_TF2.sh

    - name: Compile TF2 plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true
          
    - name: Remove SourceMod Files
      run: |
          cd ${{ github.workspace }}
          ls -la
          tar -ft sourcemod.tar.gz | xargs rm
          
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
          path: ${{ github.workspace }}
          name: TF2-compiled-plugins
          
    - name: Clean compiled directory
      run: |
          rm addons/sourcemod/scripting/compiled/*

    - name: Switch Game Mode to TF2 MVM
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to TF2 MVM";
          ./game_switcher_TF2_MVM.sh

    - name: Compile TF2 MVM plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true

    - name: Remove SourceMod Files
      run: |
          cd /
          tar --list sourcemod.tar.gz | xargs rm
          
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
          path: cd /
          name: TF2-MVM-compiled-plugins

    - name: Clean compiled directory
      run: |
          rm addons/sourcemod/scripting/compiled/*
  
    - name: Switch Game Mode to FoF
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to FoF";
          ./game_switcher_FOF.sh

    - name: Compile FoF plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true

    - name: Remove SourceMod Files
      run: |
          cd /
          tar --list sourcemod.tar.gz | xargs rm

    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
          path: /
          name: FoF-compiled-plugins

    - name: Clean compiled directory
      run: |
          rm addons/sourcemod/scripting/compiled/*
          
    - name: Switch Game Mode to CSS
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to CSS";
          ./game_switcher_CSS.sh

    - name: Compile FoF plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true

    - name: Remove SourceMod Files
      run: |
          cd /
          tar --list sourcemod.tar.gz | xargs rm
          
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
          path: /
          name: CSS-compiled-plugins

    - name: Clean compiled directory
      run: |
          rm addons/sourcemod/scripting/compiled/*
          
    - name: Switch Game Mode to CSGO
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to CSGO";
          ./game_switcher_CSGO.sh

    - name: Compile CSGO plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true
          
    - name: Remove SourceMod Files
      run: |
          cd /
          tar --list sourcemod.tar.gz | xargs rm          
          
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
          path: /
          name: CSGO-compiled-plugins

    - name: Clean compiled directory
      run: |
          rm addons/sourcemod/scripting/compiled/*
