name: War3Evo War3Source SourceMod Plugin Workflow

on:
  push:
    branches: master    

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: [ "1.9" ]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Download & Extract SourceMod 1.9
      run: |
        cd ${{ github.workspace }}
        wget "http://www.sourcemod.net/latest.php?version=1.9&os=linux" -O sourcemod-1.9-linux.tar.gz
        ls -la
        tar -xvf sourcemod-1.9-linux.tar.gz
        
    - name: Extract SourceMod as List
      run: |
        cd ${{ github.workspace }}
        tar --list -f sourcemod-1.9-linux.tar.gz > smlist19.txt
         
    - name: Give spcomp the required permissions
      run: chmod +x addons/sourcemod/scripting/spcomp_1.9.0.6261
      
    - name: Clean plugins directory
      run: |
          rm addons/sourcemod/plugins/*
          
    - name: Switch Game Mode to TF2
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to TF2";
          ./game_switcher_TF2.sh

    - name: Compile TF2 plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true
          
    - name: Clean up & Remove SM 1.9
      run: |
          cd ${{ github.workspace }}
          ls -la
          xargs rm -f < smlist19.txt || true
          rm -rf .git
          rm -rf .github
          
    - name: Create War3SourceEvo-TF2-plugins
      uses: actions/upload-artifact@v3
      with:
          path: |
            !${{ github.workspace }}/sourcemod-1.9-linux.tar.gz
            !${{ github.workspace }}/smlist19.txt
            !${{ github.workspace }}/.git
            !${{ github.workspace }}/.github
            ${{ github.workspace }}/LICENSE
            ${{ github.workspace }}/README.md
            ${{ github.workspace }}/CHANGELOG.md
            ${{ github.workspace }}/addons/
            ${{ github.workspace }}/cfg/
            ${{ github.workspace }}/sound/
          name: War3SourceEvo-TF2-plugins
          
    - name: Clean plugins directory
      run: |
          rm addons/sourcemod/plugins/*
          
    - name: Switch Game Mode to TF2 MVM
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to TF2 MVM";
          ./game_switcher_TF2_MVM.sh

    - name: Compile TF2 MVM plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true
          
    - name: Clean up & Remove SM 1.9
      run: |
          cd ${{ github.workspace }}
          ls -la
          xargs rm -f < smlist19.txt || true
          rm -rf .git
          rm -rf .github
          
    - name: Create War3SourceEvo-TF2-MVM-plugins
      uses: actions/upload-artifact@v3
      with:
          path: |
            !${{ github.workspace }}/sourcemod-1.9-linux.tar.gz
            !${{ github.workspace }}/smlist19.txt
            !${{ github.workspace }}/.git
            !${{ github.workspace }}/.github
            ${{ github.workspace }}/LICENSE
            ${{ github.workspace }}/README.md
            ${{ github.workspace }}/CHANGELOG.md
            ${{ github.workspace }}/addons/
            ${{ github.workspace }}/cfg/
            ${{ github.workspace }}/sound/
          name: War3SourceEvo-TF2-MVM-plugins

    - name: Clean plugins directory
      run: |
          rm addons/sourcemod/plugins/*
          
    - name: Switch Game Mode to FOF
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to FOF";
          ./game_switcher_FOF.sh

    - name: Compile FOF plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true
          
    - name: Clean up & Remove SM 1.9
      run: |
          cd ${{ github.workspace }}
          ls -la
          xargs rm -f < smlist19.txt || true
          rm -rf .git
          rm -rf .github
          
    - name: Create War3SourceEvo-FOF-plugins
      uses: actions/upload-artifact@v3
      with:
          path: |
            !${{ github.workspace }}/sourcemod-1.9-linux.tar.gz
            !${{ github.workspace }}/smlist19.txt
            !${{ github.workspace }}/.git
            !${{ github.workspace }}/.github
            ${{ github.workspace }}/LICENSE
            ${{ github.workspace }}/README.md
            ${{ github.workspace }}/CHANGELOG.md
            ${{ github.workspace }}/addons/
            ${{ github.workspace }}/cfg/
            ${{ github.workspace }}/sound/
          name: War3SourceEvo-FOF-plugins

    - name: Clean plugins directory
      run: |
          rm addons/sourcemod/plugins/*
          
    - name: Switch Game Mode to CSS
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to CSS";
          ./game_switcher_CSS.sh

    - name: Compile CSS plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true
          
    - name: Clean up & Remove SM 1.9
      run: |
          cd ${{ github.workspace }}
          ls -la
          xargs rm -f < smlist19.txt || true
          rm -rf .git
          rm -rf .github
          
    - name: Create War3SourceEvo-CSS-plugins
      uses: actions/upload-artifact@v3
      with:
          path: |
            !${{ github.workspace }}/sourcemod-1.9-linux.tar.gz
            !${{ github.workspace }}/smlist19.txt
            !${{ github.workspace }}/.git
            !${{ github.workspace }}/.github
            ${{ github.workspace }}/LICENSE
            ${{ github.workspace }}/README.md
            ${{ github.workspace }}/CHANGELOG.md
            ${{ github.workspace }}/addons/
            ${{ github.workspace }}/cfg/
            ${{ github.workspace }}/sound/
          name: War3SourceEvo-CSS-plugins

    - name: Clean plugins directory
      run: |
          rm addons/sourcemod/plugins/*
          
    - name: Switch Game Mode to CSGO
      run: |
          cd addons/sourcemod/scripting/
          echo -e "Switching to CSGO";
          ./game_switcher_CSGO.sh

    - name: Compile CSGO plugins
      run: |
          cd addons/sourcemod/scripting/
          echo -e "\nCompiling $file..." 
          ./compile_for_github_action.sh || true
          
    - name: Clean up & Remove SM 1.9
      run: |
          cd ${{ github.workspace }}
          ls -la
          xargs rm -f < smlist19.txt || true
          rm -rf .git
          rm -rf .github
          
    - name: Create War3SourceEvo-CSGO-plugins
      uses: actions/upload-artifact@v3
      with:
          path: |
            !${{ github.workspace }}/sourcemod-1.9-linux.tar.gz
            !${{ github.workspace }}/smlist19.txt
            !${{ github.workspace }}/.git
            !${{ github.workspace }}/.github
            ${{ github.workspace }}/LICENSE
            ${{ github.workspace }}/README.md
            ${{ github.workspace }}/CHANGELOG.md
            ${{ github.workspace }}/addons/
            ${{ github.workspace }}/cfg/
            ${{ github.workspace }}/sound/
          name: War3SourceEvo-CSGO-plugins                    